config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  

  resources :users 
  get 'profile/:id', to: 'users#show', as: 'profile'

  resources :sessions
  get 'login', to: 'sessions#login'
  get 'logout', to: 'sessions#destroy'

  resources :cards
  get 'cards/index'
  get 'cards/edit'

  resources :sharedcards
  resources :balances

end

app/models/card.rb
class Card < ActiveRecord::Base
	has_many :sharedcards
	has_many :users, through: :sharedcards

	validates :cardnum, presence: true
	validates :cardnum, length: { minimum: 16 }

	validates :cardnum, format: { with: 
		# check that credit card # entered is a valid card 
		# Includes 15-digit American Express numbers and 16-digit VISA, MasterCard, Discover, and Japan Credit Bureau card numbers. 
		/\A\b(?<!\-|\.)(?:(?:(?:4\d|5[1-5]|65)(\d\d)(?!\1{3})|35(?:2[89]|[3-8]\d)|6(?:011|4[4-9]\d|22(?:1(?!1\d|2[1-5])|[2-8]|9(?=1\d|2[1-5]))))([\ \-]?)(?<!\d\ \d{4}\ )(?!(\d)\3{3})(\d{4})\2(?!\4|(\d)\5{3}|1234|2345|3456|5678|7890)(\d{4})(?!\ \d{4}\ \d)\2(?!\6|(\d)\7{3}|1234|3456)|3[47]\d{2}([\ \-]?)(?<!\d\ \d{4}\ )(?!(\d)\9{5}|123456|234567|345678)\d{6}(?!\ \d{5}\ \d)\8(?!(\d)\10{4}|12345|56789|67890)\d)\d{4}(?!\-)(?!\.\d)\b\z/,

		message: "Please Insert a Valid Credit Card" }

	validates :cardexp, presence: true
	validates :cardexp, format: { with: /\A^(0[1-9]|1[0-2])\/?([0-9]{4}|[0-9]{2})$\z/, message: "Please Insert a Valid Expiration Date"}

	validates :cardsecuritynum, presence: true
	# before_save :card_type
	# I attached the card type to a variable in the controller, it has been linked automatically and saved
	

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
  end

  def edit
  end

  def new
    @card = Card.new
  end

  def create

    cardnum = params[:card][:cardnum]
    cardsecuritynum = params[:card][:cardsecuritynum]
    cardexp = params[:card][:cardexp]
    cardcompany = params[:card][:cardcompany]
    user_id = session[:user_id]

    # Add Card Company Automatically Based on Credit Card Pattern
    # This can be linked to jQuery for dynamic interaction as user enters card
    if cardnum =~ /\A^4[0-9]{12}(?:[0-9]{3})?$\z/
      cardcompany = "Visa"
    elsif cardnum =~ /\A^6(?:011|5[0-9]{2})[0-9]{12}$\z/
      cardcompany = "Discover"
    elsif cardnum =~ /\A^3[47][0-9]{13}$\z/
      cardcompany = "American Express"
    elsif cardnum =~ /\A^5[1-5][0-9]{14}$\z/
      cardcompany = "Mastercard"
    else
      cardCompany = "Unknown"
    end


    @card = Card.create(cardnum: cardnum, cardsecuritynum: cardsecuritynum, cardexp: cardexp, cardcompany: cardcompany, user_id: user_id)
    if @card.save
      flash[:notice] = "Card Successfully Added by User # #{user_id}"
    else
      flash[:notice] = "Error Adding New Card, Please Try Again"
    end
    redirect_to root_path
  end

  def show
    @sharedCard = Sharedcard.new
  	@thisId = session[:user_id]

    # Grant Admin Special Access to View All Cards
    if session[:user_id] == 10
      @userOwnedCards = Card.all

      # Build Array to include the id's of all cards each user owns
      userCardIdArray = []

      if @userOwnedCards.length > 0
        @userOwnedCards.each do |card|
          userCardIdArray.push(card.id)
        end
      end
    else
      #find all cards the user uploaded - loop thru all Cards where user_id is equal to session_id
      @userOwnedCards = Card.where(user_id:@thisId)

      # Build Array to include the id's of all cards each user owns
      userCardIdArray = []
      
      if @userOwnedCards.length > 0
        @userOwnedCards.each do |card|
          userCardIdArray.push(card.id)
        end
      end
    end
    # loop thru Sharedcards and see where user_id is equal to session_id - this will return a hash that contains card_id, push the card_id
    # into an array, take each card_id from that array and use that to loop thru Card model and return all card data - wrap in an IF not 
    # empty then run the loop to display data  
    sharedcardLoop = Sharedcard.where(user_id:@thisId)
    @userCardArray = []

    if sharedcardLoop.length > 0
      sharedcardLoop.each do |card|
        cardId = card.card_id 
        if !userCardIdArray.include?(cardId)
          @userCardArray.push(cardId)
        end
      end
    end    
  end

  def destroy
    @card = Card.find(params[:id])
    @sharedCard = Sharedcard.where(card_id:params[:id])
    if @sharedCard.length > 0
      @sharedCard.delete_all
    end
    @card.delete

    # @deleteCard.destroy_all
    # @deleteSharedCard.delete_all
    redirect_to card_path(session[:user_id])
    # redirect_to root_path
    flash[:notice] = 'Card Removed!'
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.erb
<h1>Cards#edit</h1>
<p>Find me in app/views/cards/edit.html.erb</p>

app/views/cards/index.html.erb
<h1>Cards#index</h1>
<p>Find me in app/views/cards/index.html.erb</p>

app/views/cards/new.html.erb
<h1>Add A New Card</h1>
<br>

<%= form_for @card do |f| %>

  <%= f.label "Enter Credit Card Number:" %>
  <%= f.text_field :cardnum %>
  <br>
  <br>

  <%= f.label "Card Security Number:" %>
  <%= f.text_field :cardsecuritynum %>  
  <br>
  <br>

  <%= f.label "Expiration Date:" %>
  <%= f.text_field :cardexp %>
  <br>
  <br>

  
  <%= f.submit "Submit"  %>

<% end %>

app/views/cards/show.html.erb
<% if session[:user_id] == 10 %>
	<h1>Admin Access - Viewing All Cards</h1>
<% else %>
	<h1>My Cards</h1>
<% end %>
<br>

<h2 class="border_test">My Cards:</h2>

  <!-- Loop thru Cards array to display all cards created by this user -->
<% if @userOwnedCards.length > 0 %>
	<div class="my_cards border_test">
		<% @userOwnedCards.each do |card| %>
			
			<p class="card_show">Card Type:</p>
			<div class="card_data"> <%= card.cardcompany %> </div>
			<br>
			<p class="card_show">Card Id:</p>
			<div class="card_data"> <%= card.id %> </div>
			<br>
			<p class="card_show">Card Expiration:</p>
			<div class="card_data"> <%= card.cardexp %> </div>
			<br>

			<!-- See who you are sharing your owned card with, if owner is not sharing with anyone then let owner know -->
			<!-- If owner of card is sharing, display users who they are currently sharing with  -->
			<% thisCardSharedWith = Sharedcard.where(card_id: card.id) %>
			<% if thisCardSharedWith.length > 0 %>
				
					<p>This Card is Currently Shared With User Id Number(s):</p>
					<% thisCardSharedWith.each do |card| %>
						<% if card.user_id != @thisId %>
							<p><%= card.user_id %></p>
						<% end %>
					<% end %>

			<% else %>
				<p>This Card is Currently Shared with No One</p>
			<% end %>
			<br>
			<%= link_to 'Share This Card With Others', root_path %>
			<br>			
			<br>
			<!-- Form to Share owner's card with other users -->
			<%= form_for @sharedCard, :url => sharedcards_path, method: :post do |f| %>
			  <%= f.label "User ID to Share With:" %>
			  <%= f.text_field :user_id %>
			  <%= f.hidden_field :card_id, :value => card.id %>
			  <br>
			  <br>
			  <%= f.submit "Share Card!"  %>
			<% end %>

			<br>
			<br>

			<% @deleteCard = Card.find(card.id) %>
			<% @deleteSharedCard = Sharedcard.where(card_id:card.id) %>

			<%= link_to 'Remove This Card', card_path(card.id), method: :delete %>
			<br>
			<hr>

		<% end %>
	</div>
<% else %>
	<div class="card_data"> No Cards Added Yet! </div>
<% end %>



  <!-- Loop thru Sharedcards array to display all cards accessible to this user -->

<h2 class="border_test">Cards Shared With Me:</h2>

<% if @userCardArray.length > 0 %>
	
	<%  for i in 0..@userCardArray.length-1 %>
		
			<p class="card_show">Shared By User Id:<%= Card.where(id:@userCardArray[i]).first.user_id  %></p>	
			<br>		

			<p class="card_show">Card Type:</p>
			<div class="card_data"> <%= Card.where(id:@userCardArray[i]).first.cardcompany %> </div>
			<br>
			<p class="card_show">Card Id:</p>
			<div class="card_data"> <%= Card.where(id:@userCardArray[i]).first.id %> </div>
			<br>
			<p class="card_show">Card Expiration:</p>
			<div class="card_data"> <%= Card.where(id:@userCardArray[i]).first.cardexp %> </div>
			<br>
			<hr>
	<% end %>
<% else %>
	<p class="card_data">No Cards Currently Being Shared With Me</p>
<% end %>

	