config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  

  resources :users 
  get 'profile/:id', to: 'users#show', as: 'profile'

  resources :sessions
  get 'login', to: 'sessions#login'
  get 'logout', to: 'sessions#destroy'

  resources :cards
  get 'cards/index'
  get 'cards/edit'

  resources :sharedcards
  resources :balances

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!--

┏┓┏┓┏┓╋╋┏┓┏┓╋╋╋┏┓
┃┃┃┃┃┃╋╋┃┃┃┃╋╋┏┛┗┓
┃┃┃┃┃┣━━┫┃┃┃┏━┻┓┏┛
┃┗┛┗┛┃┏┓┃┃┃┃┃┃━┫┃
┗┓┏┓┏┫┏┓┃┗┫┗┫┃━┫┗┓
╋┗┛┗┛┗┛┗┻━┻━┻━━┻━┛

-->
<head>
  <title>Wallet</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if session[:user_id] == 10 %>
	  <style>
	  	header {
	  		background-color: red;
	  	}

	  	.admin {
	  		float: right;
	  		margin-left: 15px;
	  	}
	  </style>
 <% end %>
</head>
<body>
	<header>
		<% if session[:user_id] == 10 %>
			<h1 class="admin">** ADMIN ACCESS **</h1>
		<% end %>
		<ul class="header_links">
			<% if session[:user_id] %>
				<li><%= link_to 'Logout', logout_path%></li>								
				<li><%= link_to 'Preferences', edit_user_path(session[:user_id]) %></li>		
				<li><%= link_to 'Upload New Card', new_card_path %></li>	
				<% if session[:user_id] == 10 %>
					<li><%= link_to 'View All Cards', card_path(session[:user_id]) %></li>											
				<% else %>					
					<li><%= link_to 'My Credit Cards', card_path(session[:user_id]) %></li>						
				<% end %>
				<li><%= link_to 'Home', root_path %></li>
			<% else %>
				<li><%= link_to 'Login', login_path %></li>
				<li><%= link_to 'Create New User', new_user_path %></li>
				<li><%= link_to 'Home', root_path %></li>
			<% end %>
		</ul>
		<%= image_tag 'wallet-logo.png', :class => 'wallet_logo' %>
	</header>


	<div class="body_content_wrapper">
		<% if flash[:notice] %>
			<p class="flash_message"><%= flash[:notice] %></p>
			<br>
		<% end %>	
		<% if flash[:alert] %>
			<p class="flash_message"><%= flash[:alert] %></p>
			<br>
		<% end %>

		<%= yield %>

	</div>
	<footer>
		<% if session[:user_id] %>
			<p>Currently Signed in as Username: <%= User.find(session[:user_id]).username %> ID: <%= User.find(session[:user_id]).id %> </p>
		<% end %>
	</footer>
</body>
</html>